# this is a more advanced and realistic example for a Docker Compose
# configuration which shows how the setup when deploying to your own
# instance looks like. Compared to the `docker-compose.yml`, it adds
# or changes the following:
#
# (1) `restart: always` to ensure services are restarted after reboot
# (2) `WEB_BASE_URL: https://npr.example.com` example for a publicly
#                    reachable HTTPS URL. Update this to your own
#                    setup and ensure that you have corresponding DNS
#                    entries in place.
# (3) Add `nginxproxy/nginx-proxy` as reverse-proxy in front of the
#     api and web containers
# (4) Add `acme-companion` which requests and automatically renews
#     Let’s Encrypt certificates for HTTPS
# (5) Add `watchtower` which automatically keeps the NodePit Runner
#     related containers up to date
# (6) Define the `DOCKER_NETWORK_MODE` the executor - this allows
#     to access containers (e.g. a database) which are defined in this
#     stack within your schedules (you can access them via hostname)
#
# NOTE: In contrast to the plain `docker-compose.yml`, this version
#       requires more adaptations and knowledge to get going.
#       Are you having issues? We’re happy to help - just open a
#       discussion on GitHub or get in touch: mail@nodepit.com

version: '3.8'

services:
  api:
    image: ghcr.io/nodepit/runner-api:1
    restart: always
    volumes:
      - api-data:/nodepit
    environment:
      # [A1] The connection URL of the MongoDB database. Make sure username and
      # password match the environment variables MONGO_INITDB_ROOT_USERNAME
      # (see M1) and MONGO_INITDB_ROOT_PASSWORD (see M2). The expected format is
      # "mongodb://<username>:<password>@mongodb/nodepit-runner?authSource=admin"
      DB_URL: mongodb://root:drnFEtX_PWKizUzKr3KT@mongodb/nodepit-runner?authSource=admin
      # [A2] The API key used by executors to receive jobs and provide run
      # results. Please make sure the provided value is equals to the API_KEY
      # configured for the executor container (see E1).
      API_KEY: nYCA3oaqhYJ__GEteWye
      # [A3] This works if you only access the Runner from your local computer -
      # if you make it accessible for other users at some point, you’ll need to
      # change this either to a hostname (`https://runner.example.com:8080`) or
      # a static IP address (this is an advanced topic - you’ll likely want to
      # set up your runner behind a reverse proxy with HTTPS)
      WEB_BASE_URL: https://npr.example.com
    depends_on:
      - mongodb
    labels:
      - com.centurylinklabs.watchtower.enable=true

  web:
    image: ghcr.io/nodepit/runner-web:1
    restart: always
    environment:
      API_BASE_URL: http://api:3000
      VIRTUAL_HOST: npr.example.com
      LETSENCRYPT_HOST: npr.example.com
      LETSENCRYPT_EMAIL: admin@example.com
    depends_on:
      - api
    labels:
      - com.centurylinklabs.watchtower.enable=true

  executor:
    image: ghcr.io/nodepit/runner-executor:1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - executor-data:/opt/data
    environment:
      API_BASE_URL: http://api:3000
      # [E1] The API key to receive jobs and provide run results from the API.
      # Please make sure the provided value is equals to the API_KEY configured
      # for the API container (see A2).
      API_KEY: nYCA3oaqhYJ__GEteWye
      SHARED_VOLUME_NAME: executor-data
      # [E3] If you are experiencing out of memory (OOM) errors, you can limit
      # the resource usage of the executor's worker containers by setting
      # resource limits in relation to your host machine. More information
      # here: https://docs.docker.com/config/containers/resource_constraints/
      # DOCKER_CPU_PERIOD: 100000
      # DOCKER_CPU_QUOTA: 85000
      # DOCKER_MEMORY: 1500000000
      DOCKER_NETWORK_MODE: nodepit-runner
    depends_on:
      - api
    deploy:
      # [E2] The number of executors that shall be started. Please adjust this
      # according to your number of schedules and server resources. You can
      # scale the number of executors later by running the Docker command
      # `docker compose scale executor=2`.
      replicas: 1
    labels:
      - com.centurylinklabs.watchtower.enable=true

  mongodb:
    image: mongo:6.0.20
    restart: always
    volumes:
      - mongodb-data:/data/db
    environment:
      # [M1] The username of the MongoDB root user. This needs to match the
      # username provided in the database url (see A1).
      MONGO_INITDB_ROOT_USERNAME: root
      # [M2] The password of the MongoDB root user. This needs to match the
      # password provided in the database url (see A1).
      MONGO_INITDB_ROOT_PASSWORD: drnFEtX_PWKizUzKr3KT

  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6.4
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
    labels:
      - com.github.nginx-proxy.nginx=true

  acme-companion:
    image: nginxproxy/acme-companion:2.5.1
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  watchtower:
    image: containrrr/watchtower:1.7.1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --label-enable --cleanup

volumes:
  mongodb-data:
  api-data:
  executor-data:
    name: executor-data
  certs:
  vhost:
  html:
  acme:

networks:
  default:
    name: nodepit-runner
